jobQueue:
    databaseHost: postgres://postgres:password@0.0.0.0:5432/jobs?sslmode=disable
    queues: null
    workers:
        emailWorker:
            devMode: true
            fromEmail: no-reply@example.com
            testDir: fixtures/email
            token: ""
refreshInterval: 600000000000
